---

- name: installing apache
  hosts: all
  remote_user: ravi
  become: true

  tasks:
    - name: installing apach2
      apt: name=apache2 state=present
    - name: strating the service
      service: name=apache2 state=started
