---

- name: installing apache
  hosts: all
  ansible_become: yes
  ansible_become_method: su
  ansible_become_user: root
  ansible_become_pass: admin@123
  tasks:
    - name: installing apach2
      apt: name=apache2 state=present
    - name: strating the service
      service: name=apache2 state=started
